export enum QuanterDeliver{
    LOCAL_TRIP ="LOCAL_TRIP",
    NATIONAL_TRIP ="NATIONAL_TRIP",
    LOCAL_COURIER ="LOCAL_COURIER",
    NATIONAL_COURIER ="NATIONAL_COURIER",
    LOCAL_RENTAL ="LOCAL_COURIER",
    NATIONAL_RENTAL ="NATIONAL_COURIER",
}

